#端口号
server:
  port: 80
  #solr
spring:
  jms:
    #发布订阅模式
    pub-sub-domain: true
  data:
    solr:
    host: http://192.168.25.125:8080/solr/item
  activemq:
    broker-url: tcp://192.168.25.125
    pool:
      enabled: true
      max-connections: 3000
    packages:
      trust-all: true
